parameters:
  ######## User related parameters ########
  resp_amp_factor: 1.0
  state_model_cls: ObservedUserState
  choice_model_cls: NCFChoiceModel
  response_model_cls: WeightedCosineResponseModel
  ######## Environment related parameters ########
  num_users: 5000
  sess_budget: 200
  slate_size: 10
  num_item_features: 50
  num_candidates: 2000
  num_user_features: 20
  alpha_response: 0.5
  ######## Training related parameters ########
  replay_memory_capacity: 1000
  batch_size: 256
  gamma: 1.0
  tau: 0.001
  lr: 1e-3
  num_episodes: 50000
  warmup_batches: 1
  device: "cuda:0"  
  ######## Models related parameters ########
  slate_gen_model_cls: TopKGreedySlateGenerator
  ######## Wolpertinger policy ########
  nearest_neighbours: 60
  ######## Seed ########
  seeds: [5]
  #[5, 7, 42, 97, 33]
  #[5, 7, 42, 97, 33]
  #test=[140, 184, 30, 62, 4]
  #test = [27,29,31]
  #[5,7,42,97,99]
  #[5,7,42,97, 33]
  #[5, 7, 9, 11, 13, 17]
  #[5, 7, 77, 79, 81, 42, 11, 13, 17]
  ######## Grouping ########
  grouping: "Proto-Slate1"
  